# Broadcasting and vectorization

In [4]:
[1,2]+[3,4]
a, b=[1,2], [3,4]
total=[]
for i in range(2):
    total.append(a[i]+b[i])
total

[4, 6]

In [5]:
#zip method
[a+b for a, b in zip(a,b)]

[4, 6]

# Boradcasting

In [6]:
import numpy as np

In [9]:
arr1=np.arange(9).reshape(3,3)
arr2=np.arange(3)
print(arr1)
print(arr2)
arr1+arr2

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

# vectorizaion

In [11]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr1+100

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108]])

In [13]:
arr1*100

array([[  0, 100, 200],
       [300, 400, 500],
       [600, 700, 800]])

In [14]:
arr1/100

array([[0.  , 0.01, 0.02],
       [0.03, 0.04, 0.05],
       [0.06, 0.07, 0.08]])

In [15]:
a1=np.arange(9).reshape(3,3)
a2=np.arange(9,18).reshape(3,3)
print(a1)
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [16]:
a1+a2

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [17]:
a1=np.arange(4)
a2=np.arange(4,8)
print(a1)
print(a2)

[0 1 2 3]
[4 5 6 7]


In [18]:
#dot product
np.dot(a1,a2)

np.int64(38)

In [19]:
a1=np.arange(9).reshape(3,3)
a2=np.arange(9,27, 2).reshape(3,3)
print(a1)
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 11 13]
 [15 17 19]
 [21 23 25]]


In [20]:
np.dot(a1,a2)

array([[ 57,  63,  69],
       [192, 216, 240],
       [327, 369, 411]])

In [22]:
a1=np.arange(8).reshape(2,2,2)
a2=np.arange(1,3)
print(a1)
print(a2)
print(a1.shape)
print(a2.shape)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[1 2]
(2, 2, 2)
(2,)


In [23]:
np.dot(a1,a2)

array([[ 2,  8],
       [14, 20]])

In [26]:
def cube(x:int):
    return x**3
for ele in [1,2,3,4,5]:
    print(cube(ele))

1
8
27
64
125


In [27]:
cube_vec=np.vectorize(cube)
cube_vec([1,2,3,4,5])

array([  1,   8,  27,  64, 125])