In [2]:
import numpy as np

### Identity Matrix


In [3]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.diagonal(arr)

array([0, 4, 8])

# Linear Algebra

In [8]:
arr=np.arange(1,5).reshape(2,2)
arr

array([[1, 2],
       [3, 4]])

In [ ]:
#calculating the determinant of a matrix
np.linalg.det(arr)

np.float64(-2.0000000000000004)

In [10]:
#calculating the inverse of a matrix
np.linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.linalg.det(arr)
# the determinant of a matrix is zero, the matrix is singular and its inverse does not exist

np.float64(0.0)

In [13]:
np.linalg.inv(arr)

LinAlgError: Singular matrix

In [14]:
arr=np.random.random_integers(1,10,9).reshape(3,3)
arr

/tmp/ipykernel_68291/219862043.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  arr=np.random.random_integers(1,10,9).reshape(3,3)


array([[ 8,  1,  5],
       [ 6,  1,  8],
       [10,  3,  7]])

In [15]:
np.linalg.det(arr)

np.float64(-58.000000000000036)

In [16]:
np.linalg.inv(arr)

array([[ 0.29310345, -0.13793103, -0.05172414],
       [-0.65517241, -0.10344828,  0.5862069 ],
       [-0.13793103,  0.24137931, -0.03448276]])

In [17]:
arr=np.random.random_integers(1,10,9).reshape(3,3)
arr

/tmp/ipykernel_68291/219862043.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  arr=np.random.random_integers(1,10,9).reshape(3,3)


array([[3, 8, 2],
       [6, 7, 1],
       [7, 1, 2]])

### Tranpose
- convert row to column and vice-versa

In [18]:
#transpose of a matrix
arr.T

array([[3, 6, 7],
       [8, 7, 1],
       [2, 1, 2]])

In [19]:
np.transpose(arr)

array([[3, 6, 7],
       [8, 7, 1],
       [2, 1, 2]])

## Eigen vector


In [21]:
# A * eigen_vector = eigen_value * eigen_vector
# A * V = V * D
# A = matrix
# V = eigen vector
# D = eigen value
eigen_val, eigen_vector = np.linalg.eig(arr)
eigen_val, eigen_vector

(array([13.1689288 , -3.22038142,  2.05145262]),
 array([[-0.60713974, -0.59942646,  0.04240815],
        [-0.66180214,  0.2784762 , -0.24704703],
        [-0.43977183,  0.75042583,  0.96807506]]))

In [23]:
#solve the linear equation
#2x+3y=10
#x-y=2

coeff = np.array([[2,3],[1,-1]])
y = np.array([10,2])
x,y=np.linalg.solve(coeff,y)
x,y

(np.float64(3.2), np.float64(1.2))

In [ ]:
#x+y-2z=7
#-2x+3y+z=7

In [24]:
a,b=np.arange(4).reshape(2,2), np.arange(4,8).reshape(2,2)
a,b

(array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]))

In [25]:
a@b

array([[ 6,  7],
       [26, 31]])