#Numpy

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]
arr=np.array(l)
type(arr), type(l)

(numpy.ndarray, list)

In [4]:
np.array((1,2,3,4)) #error

array([1, 2, 3, 4])

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr.shape

(4,)

In [7]:
arr.ndim

1

In [10]:
matrix_list=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]
matrix=np.array(matrix_list)
matrix
matrix.shape

(3, 3)

In [12]:
matrix.argmax()
matrix.argmin()

np.int64(0)

In [13]:
#converting to float
matrix.astype(np.float64)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [15]:
l=list(range(1,10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
np.arange(1,10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [20]:
np.linspace(1,10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [21]:
#python all and any
if []:
    print("empty list")
else:
    print("not empty list")

not empty list


In [27]:
l=[True, [1], {"name": "tilak"}, 4, "Tilak", 0]
all(l), any(l)

(False, True)

In [29]:
np.all(matrix), np.any(matrix)

(np.True_, np.True_)

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((2,3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [32]:
np.ones((2,3), dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [34]:
arr3 = np.arange(12,)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
arr3_r1=arr3.reshape(2,3, 2)

In [43]:
print(arr3_r1.shape)
print(arr3_r1[0])

(2, 3, 2)
[[0 1]
 [2 3]
 [4 5]]
