In [1]:
import numpy as np

In [3]:
arr1d = np.arange(18).astype(np.str_)
arr1d

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17'], dtype='<U21')

In [6]:
#2d indexing
l=[
    [1,2,3],
    [4,5,6],
]
l[1][1]

5

In [9]:
arr2d = np.array(l)
arr2d[1, 1]

np.int64(5)

In [11]:
#3d
l=[
    [
        [1,2,3, 4],
        [5,6,7, 8],
    ],
    [
        [9,10,11, 12],
        [13,14,15, 16],
    ],
]
l[0][0][0]

1

In [12]:
#3d indexing
arr3d = np.array(l)
arr3d[0, 0, 0]

np.int64(1)

In [14]:
arr_3d_2 = np.arange(18).reshape(3, 6, 1)
arr_3d_2[1,4,0]

np.int64(10)

In [22]:
#slicing
#1d
arr1d=np.arange(12)
print(arr1d)
arr1d[1:6:-1]

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([], dtype=int64)

In [29]:
arr2d=np.array([
    [1,2,3],
    [4,5,6],
])
arr2d[0:2, 0:1]
arr2d[0:2, 0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr=np.arange(36).reshape(6, 6)
print(arr)
arr[4:,4:]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[28, 29],
       [34, 35]])

In [33]:
#3d
arr3d=np.arange(36).reshape(3, 2, 6)
print(arr3d)
arr3d[0:2:, ::, 1:5]

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


array([[[ 1,  2,  3,  4],
        [ 7,  8,  9, 10]],

       [[13, 14, 15, 16],
        [19, 20, 21, 22]]])

In [35]:
#REshaping
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
arr4d = arr.reshape(3, 2,2, 1)
arr4d

array([[[[ 0],
         [ 1]],

        [[ 2],
         [ 3]]],


       [[[ 4],
         [ 5]],

        [[ 6],
         [ 7]]],


       [[[ 8],
         [ 9]],

        [[10],
         [11]]]])

In [40]:
arr4d.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
arr.reshape(2,-1, -1)

ValueError: can only specify one unknown dimension

In [36]:
arr.shape

(12,)