# Mathematical and statistical operations 

In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
np.add(a1,a2)

array([5, 7, 9])

In [3]:
np.subtract(a1,a2)

array([-3, -3, -3])

In [4]:
np.multiply(a1,a2)

array([ 4, 10, 18])

In [5]:
np.divide(a1,a2)

array([0.25, 0.4 , 0.5 ])

In [6]:
np.divmod(a1,a2)

(array([0, 0, 0]), array([1, 2, 3]))

# Statistical

In [8]:
np.sum(np.arange(10))

np.int64(45)

In [9]:
a1=np.random.randint(1,100)
a1

44

In [32]:
np.random.seed(0)
np.random.random(10)
np.random.uniform(1,100,10)

array([79.38077877, 53.36059706, 57.23641155, 92.63406719,  8.03256976,
        9.62580067,  3.00162135, 83.42936471, 78.03751834, 87.13120268])

In [35]:
np.mean(np.random.randint(1,100,10))

np.float64(27.6)

In [41]:
a1=[1,2,3,4,5]
np.max(a1)
np.min(a1)
np.argmax(a1)
np.argmin(a1)

np.int64(0)

In [43]:
a1=np.arange(0,25).reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
np.max(a1)
np.argmax(a1)
np.unravel_index(24, a1.shape)

(np.int64(4), np.int64(4))

In [3]:
arr = np.arange(0, 25).reshape(5, 5)    
np.log(arr)

/tmp/ipykernel_22967/1934879271.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383]])